# PARA DESENVOLVIMENTO
version: '3.3'
services:
  app:
    image: node:16-alpine
    
    # configs adicionais
    container_name: mentoria_express
    working_dir: /app
    restart: on-failure

    # iterativo
    stdin_open: true
    tty: true

    # o que vai rodar ao iniciar o container
    command: sh

    environment:
      - DB_PASSWORD=password

    ports:
      - 3001:3001
    depends_on:
      - db
    volumes:
      - ./:/app
  db:
    image: mysql:5.7

    # configs adicionais
    container_name: mentoria_express_db
    restart: on-failure

    volumes:
      - ./database:/var/lib/mysql

    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306